
  version: '2'

  networks:
    byfn:

  services:
  
    fabric-ca-server:
      image: hyperledger/fabric-ca:1.4
      container_name: fabric-ca-server
      ports:
        - "7054:7054"
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=fabric-ca-server
        - FABRIC_CA_SERVER_PORT=7054
        - FABRIC_CA_SERVER_TLS_ENABLED=false
        # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
        # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/new-fabric-ca-server-config/ca.org1.example.com-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/new-fabric-ca-server-config/0864c79813168958f193f9ccf312cb5ae06a435c12dac4a858fee139e633decf_sk
      volumes:
        - /home/user/workspace/github/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/new-fabric-ca-server-config
        # - "./fabric-ca-server:/etc/hyperledger/fabric-ca-server"
        # - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      command: sh -c 'fabric-ca-server start -b admin:adminpw'
      # command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
      networks:
        - byfn